version: '3.8'

services:
  nginx:
    container_name: demo-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../laravel:/var/www/laravel
      - ./nginx/php.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: demo-php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../laravel:/var/www/laravel
      - ./php/php/docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    working_dir: /var/www/laravel

  mysql:
    container_name: demo-mysql
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
